version: 1.0.{build}
skip_non_tags: true
image: Visual Studio 2019
configuration: Release
install:
- cmd: nuget sources add -Name myget.skyapm -Source https://www.myget.org/F/skyapm-dotnet
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: oPAtTNZVZUAmYoenPdNZFz7pBm0mEhWCknYREwmhDLWCYGOqEGGhVa5Ik1f6EwGG
  skip_symbols: true
  artifact: /.*\.nupkg/